name: Publish website at euroscipy.org

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install Python and pipenv
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: make install

    - name: sync website with rsync
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_KNOWN_HOST: ${{ secrets.SSH_KNOWN_HOST }}
      run: |
        mkdir -p ~/.ssh
        python3 write_key.py
        chmod og-rwx ~/.ssh/id_rsa ~/.ssh/known_hosts
        wc -l ~/.ssh/id_rsa ~/.ssh/known_hosts
        ls -lh ~/.ssh
        make rsync_upload

